repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: detect-private-key
  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-config
          - mdformat-footnote
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-frontmatter
        args: [--number]
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/btford/write-good
    rev: v1.0.8
    hooks:
      - id: write-good
        args: [--no-passive]
  - repo: https://github.com/oxc-project/mirrors-oxlint
    rev: v1.86.0
    hooks:
      - id: oxlint
  - repo: https://github.com/oxc-project/mirrors-oxfmt
    rev: v0.71.0
    hooks:
      - id: oxfmt
  - repo: local
    hooks:
      - id: esupgrade
        name: esupgrade
        description: 'Upgrade your ECMAScript syntax to Baseline.'
        entry: npx .
        args: [--write]
        language: system
        types_or: [javascript, jsx, ts, tsx]
        require_serial: true
ci:
  autoupdate_schedule: weekly
  skip:
    - no-commit-to-branch
    - write-good
    - esupgrade
